---
name: Publish Doc-Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    uses: RelativeProgramming/quartz-gh-pages-action